
- name: bigip configuration sync
  hosts: all
  strategy: linear
  
  tasks:
    - name: collect sync status from bigip devices
      bigip_command:
        provider:
          server: "{{ansible_host}}"
          validate_certs: no
          user: "{{ansible_user}}"
          password: "{{ansible_password}}"
        commands: show cm sync-status
      register: sync_status_results
      delegate_to: localhost
      tags:
        - bigip_config_sync
    
    - name: rewrite facts based on sync status
      set_fact:
        bigip_device: "{{sync_status_results.stdout.0 | regex_search('Recommended\\saction:\\sSynchronize\\s([\\w\\d\\-]+)\\.local\\sto\\sgroup\\s([\\w\\-]+)', '\\1', ignorecase=true) | first}}"
        bigip_device_group: "{{sync_status_results.stdout.0 | regex_search('Recommended\\saction:\\sSynchronize\\s([\\w\\d\\-]+)\\.local\\sto\\sgroup\\s([\\w\\-]+)', '\\2', ignorecase=true) | first}}" 
      register: set_fact_results
      delegate_to: localhost
      ignore_errors: yes
      tags:
        - bigip_config_sync
        
    - name: bigip configuration sync
      bigip_configsync_action:
        provider:
          server: "{{ansible_host}}"
          validate_certs: no
          user: "{{ansible_user}}"
          password: "{{ansible_password}}"
        sync_device_to_group: yes
        device_group: "{{bigip_device_group}}"
      when: 
        - not (set_fact_results is failed)
        - (inventory_hostname is eq bigip_device)
      delegate_to: localhost
      tags:
        - bigip_config_sync
